name: Build and Deploy Website

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v2

      - name: Install pandoc
        run: sudo apt install -y pandoc

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install requirements
        shell: bash -l {0}
        run: |
          python -m pip install -r requirements.txt

      - name: Build Documentation
        run: |
          make html

      - name: GitHub Pages Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        if: github.event_name == 'push'
        with:
          branch: gh-pages
          folder: build/html
