name: Build and Deploy Website

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v2

      - name: Install pandoc
        run: sudo apt install -y pandoc

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install requirements
        shell: bash -l {0}
        run: |
          python -m pip install -r requirements.txt

      - name: Build Documentation
        run: |
          make html

      #3- name: GitHub Pages Deploy
      #3  uses: JamesIves/github-pages-deploy-action@4.1.1
      #3  if: github.event_name == 'push'
      #3  with:
      #3    branch: gh-pages
      #3    folder: docs/qcfractal/build/html
